-- DB2 init script
-- Note: DB2 testcontainer creates the database. We create schema objects.

CREATE SCHEMA DDL_TEST;

-- Sequence
CREATE SEQUENCE DDL_TEST.EMP_SEQ START WITH 1000 INCREMENT BY 1;

-- Departments table
CREATE TABLE DDL_TEST.DEPARTMENTS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(100) NOT NULL,
    CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (ID)
);

-- Employees table
CREATE TABLE DDL_TEST.EMPLOYEES (
    ID INTEGER NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255),
    SALARY DECIMAL(10,2),
    DEPARTMENT_ID INTEGER,
    HIRE_DATE DATE DEFAULT CURRENT DATE,
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_EMPLOYEES PRIMARY KEY (ID),
    CONSTRAINT UQ_EMP_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DDL_TEST.DEPARTMENTS(ID)
);

ALTER TABLE DDL_TEST.EMPLOYEES ADD CONSTRAINT CHK_SALARY CHECK (SALARY > 0);

-- Composite index
CREATE INDEX DDL_TEST.IDX_EMP_NAME ON DDL_TEST.EMPLOYEES(LAST_NAME, FIRST_NAME);

-- View
CREATE VIEW DDL_TEST.ACTIVE_EMPLOYEES AS
    SELECT ID, FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID
    FROM DDL_TEST.EMPLOYEES
    WHERE IS_ACTIVE = 'Y';
