-- Oracle init script for DDL_TEST schema
-- Note: Oracle XE Free container runs as system user. We create a user/schema.

-- Create test user/schema
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER DDL_TEST IDENTIFIED BY test_password DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE SEQUENCE TO DDL_TEST;
GRANT SELECT ON SYS.DBA_TABLES TO DDL_TEST;
GRANT EXECUTE ON DBMS_METADATA TO DDL_TEST;

-- Switch to test schema
ALTER SESSION SET CURRENT_SCHEMA = DDL_TEST;

-- Sequence
CREATE SEQUENCE DDL_TEST.EMP_SEQ START WITH 1000 INCREMENT BY 1;

-- Departments table
CREATE TABLE DDL_TEST.DEPARTMENTS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL
);

-- Employees table
CREATE TABLE DDL_TEST.EMPLOYEES (
    ID NUMBER DEFAULT DDL_TEST.EMP_SEQ.NEXTVAL NOT NULL,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(255),
    SALARY NUMBER(10,2),
    DEPARTMENT_ID NUMBER,
    HIRE_DATE DATE DEFAULT SYSDATE,
    IS_ACTIVE CHAR(1) DEFAULT 'Y',
    CONSTRAINT PK_EMPLOYEES PRIMARY KEY (ID),
    CONSTRAINT UQ_EMP_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CHK_SALARY CHECK (SALARY > 0),
    CONSTRAINT CHK_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT FK_DEPT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DDL_TEST.DEPARTMENTS(ID)
);

-- Composite index
CREATE INDEX DDL_TEST.IDX_EMP_NAME ON DDL_TEST.EMPLOYEES(LAST_NAME, FIRST_NAME);

-- Function-based index
CREATE INDEX DDL_TEST.IDX_EMP_UPPER ON DDL_TEST.EMPLOYEES(UPPER(LAST_NAME));

-- Partitioned table
CREATE TABLE DDL_TEST.SALES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    SALE_DATE DATE NOT NULL,
    AMOUNT NUMBER(10,2),
    REGION VARCHAR2(50)
) PARTITION BY RANGE (SALE_DATE) (
    PARTITION SALES_2023 VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD')),
    PARTITION SALES_2024 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD'))
);

-- View
CREATE VIEW DDL_TEST.ACTIVE_EMPLOYEES AS
    SELECT ID, FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID
    FROM DDL_TEST.EMPLOYEES
    WHERE IS_ACTIVE = 'Y';

-- Materialized view
CREATE MATERIALIZED VIEW DDL_TEST.MV_DEPT_SUMMARY AS
    SELECT D.NAME AS DEPARTMENT_NAME, COUNT(E.ID) AS EMPLOYEE_COUNT
    FROM DDL_TEST.DEPARTMENTS D
    LEFT JOIN DDL_TEST.EMPLOYEES E ON D.ID = E.DEPARTMENT_ID
    GROUP BY D.NAME;
